require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

# RSpecでのブロック行数チェックを無効化
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'


AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.5
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'app/javascript/**/**/**/**'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - !ruby/regexp /old_and_unused\.rb$/

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Security:
  Enabled: true

Rails:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: false


# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# コメントの先頭にホワイトスペースを入れること

Layout/LeadingCommentSpace:
  Enabled: true
  Exclude: []


# Hashを書く時はキーを左揃えにし、valueの位置を整える

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 20

RSpec/ContextWording:
  Enabled: false

